global:
  scrape_interval:     15s


rule_files:
  - "alert_rules.yml"


scrape_configs:
  #scrape prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  #scrape django webapp
  - job_name: 'django-app'
    static_configs:
      - targets:  ['django-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s


# Let Prometheus to show us alerts
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

